config/routes.rb
Rails.application.routes.draw do

  #admin_users devise & end_users devise
  devise_for :admin_users, controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  # top page
  root 'homes#top'
  get 'homes/about'
  get 'homes/size'
  get 'homes/ship_pay'

  # ec page
  resources :items, only: [:index, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :genres, only: [:show]
  delete 'cart_item/destroy_all', to: 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :create, :update, :destroy]
  get 'orders/input_address', to: 'orders#input_address'
  post 'orders/create_address', to: 'orders#create_address'
  post 'orders/create_session', to: 'orders#create_session'
  get 'orders/display', to: 'orders#display'
  get 'orders/thanks', to: 'orders#thanks'
  resources :orders, only: [:index, :show, :create]
  
  # end_user mypage
  resources :end_users, only: [:show, :edit, :update, :destroy] do
    resources :likes, only: [:index]
    collection do
      get :confirm
    end
  end
  
  # admin page
  namespace :admin do
    resources :items, only: [:index, :show, :new, :edit, :create, :update]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :materials, only: [:index, :edit, :update, :create]
    resources :ribbons, only: [:index, :edit, :update, :create]
    patch 'orders/:id/production', to: 'orders#production_update', as: 'order_production'
    resources :orders, only: [:index, :show, :update]
    resources :end_users, only: [:index]
  end
  
  # shipping address
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :end_user
  
  # paranoia
  acts_as_paranoid

  validates :zipcode, format: { with: /\A\d{7}\z/, message: 'は7桁で入力してください'}
  validates :address, :name, presence: true

  def input_view_address
    zipcode.to_s.insert(3, '-')
    "〒" + self.zipcode + " " +self.address + " " + self.name.to_s
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :end_user
  belongs_to :item
  belongs_to :material
  belongs_to :ribbon
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  acts_as_paranoid
  
  validates :last_name, :first_name, presence: true
  validates :last_name_kana, :first_name_kana, format: { with: /\A[ｧ-ﾝﾞﾟ]+\z/, message: 'は半角ｶﾅで入力してください' } #半角ｶﾀｶﾅ
  validates :zipcode, format: { with: /\A\d{7}\z/, message: 'は7桁で入力してください'}  #半角英数字７桁
  validates :address, presence: true
  validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'は10桁か11桁で入力してください' } #半角英数字10桁か11桁
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence:true

  enum status: { "無効": 0, "有効": 1 }

  #ジャンルが無効の場合アイテムを販売停止中にする
  after_update do
    if self.status == "無効"
      self.items.each {|item| item.update(status: "販売停止中")}
    else
      self.items.each {|item| item.update(status: "販売中")}
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :likes, dependent: :destroy
  def like_user(end_user_id)
    likes.find_by(end_user_id: end_user_id)
  end

  validates :image, :name, :caption, :genre_id, presence:true
  validates :price, format: { with: /\A[0-9]+\z/, message: 'は半角英数字で入力してください' } 
  validates :status, presence:true

  attachment :image

  enum status: { "販売停止中": 0, "販売中": 1 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :end_user
  belongs_to :item, counter_cache: :likes_count
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :cart_items
  validates :name, presence:true
  validates :image, presence:true
  
  attachment :image

  enum status: { "無効": 0, "有効": 1 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :end_user
  has_many   :order_details, dependent: :destroy

  validates :zipcode, :address, :name, presence: true
  
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }

  after_update do
    if status == "入金待ち"
      order_details.each {|order_detail| order_detail.update(production_status: "着手不可")}
    elsif status == "入金確認"
      order_details.each {|order_detail| order_detail.update(production_status: "製作待ち")}
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order

  enum production_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

  after_update do
    order_details = order.order_details
    if order_details.any? {|order_detail| order_detail.production_status == "製作中"} == true
      order.update(status: "製作中")
    elsif order_details.all? {|order_detail| order_detail.production_status == "製作完了"} == true
      order.update(status: "発送準備中")
    end
  end
end

app/models/ribbon.rb
class Ribbon < ApplicationRecord
  has_many :cart_items
  validates :color, presence:true
  validates :image, presence:true

  attachment :image

  enum status: { "無効": 0, "有効": 1 }
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_end_user!

  def index
    @cart_items = CartItem.where(end_user_id: current_end_user.id)

    @cart_items_sum_price = 0
    @cart_items.each do |cart_item|
      @cart_items_sum_price += cart_item.item.price
    end
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.end_user_id = current_end_user.id
    if @cart_item.save
      redirect_to cart_items_path, success: "【商品をカートに追加しました】"
    else
      render :show
    end
  end

  def update
    cart_item = CartItem.find(params[:id])
    cart_item.update(cart_item_params)
    redirect_to cart_items_path, info: "【サイズを変更しました】"
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path, warning: "【カートアイテムを削除しました】"
  end

  def destroy_all
    current_cart_items = CartItem.where(end_user_id: current_end_user.id)
    current_cart_items.destroy_all
    redirect_to cart_items_path, warning: "【カートを空にしました】"
  end

  private
  
  def cart_item_params
    params.require(:cart_item).permit(:end_user_id, :item_id, :material_id, :ribbon_id, :size)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order(created_at: :desc).limit(4)
    @item_rank = Item.order(likes_count: :desc).limit(3)
  end

  def about
  end

  def size
  end

  def ship_pay
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}円（税込）"
  end

  def converting_to_jpy_notax(price)
    "#{price.to_s(:delimited, delimiter: ',')}円"
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/cart_items/index.html.erb
<div class="row">
  <div class="col-12">
    <h1>ショッピングカート</h1>
    <div class="col-2 offset-10">
      <% if @cart_items != [] %> <%# カートが空のときは非表示 %>
        <%= link_to 'カートを空にする', cart_item_destroy_all_path, method: :delete, data: {confirm: 'カートを空にしてよろしいですか？'}, class: "btn-sm btn-primary" %>
      <% end%>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th>商品名</th>
          <th>生地</th>
          <th>リボン</th>
          <th>税込価格</th>
          <th>サイズ</th>
          <th></th>
        </tr>
      </thead>
      <% @cart_items.each do |cart_item| %>
        <tr>
          <td><%= attachment_image_tag cart_item.item,:image, :fill, 50, 50, alt: "アイテム画像" %><%= cart_item.item.name %></td>
          <td class="small"><%= attachment_image_tag cart_item.material,:image, :fill, 40, 30, alt: "生地画像" %>
          <br><%= cart_item.material.name %></td>
          <td class="small"><%= attachment_image_tag cart_item.ribbon, :image, :fill, 40, 30, alt: "リボン画像" %>
          <br><%= cart_item.ribbon.color %></td>
          <td class="align-middle"><%= converting_to_jpy(cart_item.item.price) %></td>
          <td class="align-middle">
            <%= form_for cart_item do |f|%> 
              <%= f.select :size, [["SS","SS"], ["S","S"], ["M","M"], ["L","L"], ["DM","DM"]] %>
              <%= f.submit "変更", class: "btn btn-primary"%>
            <% end %>
          </td>
          <td class="align-middle"><%= link_to '削除する', cart_item_path(cart_item), method: :delete, data: {confirm: '商品を削除してよろしいですか？'}, class: "btn-sm btn-primary" %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <%= link_to '買い物を続ける', items_path, class: "btn btn-primary" %>
    <div class="offset-9">
      <table class="table table-bordered">
        <tr>
          <th>合計金額</th>
          <td><%= converting_to_jpy(@cart_items_sum_price) %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-4 offset-5">
    <% if @cart_items != [] %> <%# カートが空のときは非表示 %>
      <%= link_to '配送先の選択へ進む', orders_input_address_path, class: "btn btn-primary" %>
    <% end%>
  </div>
</div>