config/routes.rb
Rails.application.routes.draw do

  #admin_users devise & end_users devise
  devise_for :admin_users, controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  # top page
  root 'homes#top'
  get 'homes/about'
  get 'homes/size'
  get 'homes/ship_pay'

  # ec page
  resources :items, only: [:index, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :genres, only: [:show]
  delete 'cart_item/destroy_all', to: 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :create, :update, :destroy]
  get 'orders/input_address', to: 'orders#input_address'
  post 'orders/create_address', to: 'orders#create_address'
  post 'orders/create_session', to: 'orders#create_session'
  get 'orders/display', to: 'orders#display'
  get 'orders/thanks', to: 'orders#thanks'
  resources :orders, only: [:index, :show, :create]
  
  # end_user mypage
  resources :end_users, only: [:show, :edit, :update, :destroy] do
    resources :likes, only: [:index]
    collection do
      get :confirm
    end
  end
  
  # admin page
  namespace :admin do
    resources :items, only: [:index, :show, :new, :edit, :create, :update]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :materials, only: [:index, :edit, :update, :create]
    resources :ribbons, only: [:index, :edit, :update, :create]
    patch 'orders/:id/production', to: 'orders#production_update', as: 'order_production'
    resources :orders, only: [:index, :show, :update]
    resources :end_users, only: [:index]
  end
  
  # shipping address
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :end_user
  
  # paranoia
  acts_as_paranoid

  validates :zipcode, format: { with: /\A\d{7}\z/, message: 'は7桁で入力してください'}
  validates :address, :name, presence: true

  def input_view_address
    zipcode.to_s.insert(3, '-')
    "〒" + self.zipcode + " " +self.address + " " + self.name.to_s
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :end_user
  belongs_to :item
  belongs_to :material
  belongs_to :ribbon
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  acts_as_paranoid
  
  validates :last_name, :first_name, presence: true
  validates :last_name_kana, :first_name_kana, format: { with: /\A[ｧ-ﾝﾞﾟ]+\z/, message: 'は半角ｶﾅで入力してください' } #半角ｶﾀｶﾅ
  validates :zipcode, format: { with: /\A\d{7}\z/, message: 'は7桁で入力してください'}  #半角英数字７桁
  validates :address, presence: true
  validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'は10桁か11桁で入力してください' } #半角英数字10桁か11桁
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence:true

  enum status: { "無効": 0, "有効": 1 }

  #ジャンルが無効の場合アイテムを販売停止中にする
  after_update do
    if self.status == "無効"
      self.items.each {|item| item.update(status: "販売停止中")}
    else
      self.items.each {|item| item.update(status: "販売中")}
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :likes, dependent: :destroy
  def like_user(end_user_id)
    likes.find_by(end_user_id: end_user_id)
  end

  validates :image, :name, :caption, :genre_id, presence:true
  validates :price, format: { with: /\A[0-9]+\z/, message: 'は半角英数字で入力してください' } 
  validates :status, presence:true

  attachment :image

  enum status: { "販売停止中": 0, "販売中": 1 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :end_user
  belongs_to :item, counter_cache: :likes_count
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :cart_items
  validates :name, presence:true
  validates :image, presence:true
  
  attachment :image

  enum status: { "無効": 0, "有効": 1 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :end_user
  has_many   :order_details, dependent: :destroy

  validates :zipcode, :address, :name, presence: true
  
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }

  after_update do
    if status == "入金待ち"
      order_details.each {|order_detail| order_detail.update(production_status: "着手不可")}
    elsif status == "入金確認"
      order_details.each {|order_detail| order_detail.update(production_status: "製作待ち")}
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order

  enum production_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

  after_update do
    order_details = order.order_details
    if order_details.any? {|order_detail| order_detail.production_status == "製作中"} == true
      order.update(status: "製作中")
    elsif order_details.all? {|order_detail| order_detail.production_status == "製作完了"} == true
      order.update(status: "発送準備中")
    end
  end
end

app/models/ribbon.rb
class Ribbon < ApplicationRecord
  has_many :cart_items
  validates :color, presence:true
  validates :image, presence:true

  attachment :image

  enum status: { "無効": 0, "有効": 1 }
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin_user!

  def index
    @items = Item.all.order('created_at DESC')
  end

  def edit
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), success: "【アイテムを追加しました】"
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), info: "【アイテムを変更しました】"
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :genre_id, :caption, :status, :price, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order(created_at: :desc).limit(4)
    @item_rank = Item.order(likes_count: :desc).limit(3)
  end

  def about
  end

  def size
  end

  def ship_pay
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @genres = Genre.all
    # 販売中のアイテム
    @active_items = Item.where(status: 1).page(params[:page]).per(8).order('created_at DESC')
    # 販売停止中のアイテム
    @items = Item.where(status: 0).page(params[:page]).per(6).order('created_at DESC')
    # アイテム表示件数
    @item_count = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new

    # status: 1 = 有効
    @active_materials = Material.where(status: 1)
    @active_ribbons = Ribbon.where(status: 1)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}円（税込）"
  end

  def converting_to_jpy_notax(price)
    "#{price.to_s(:delimited, delimiter: ',')}円"
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/items/index.html.erb
<ul class="nav navbar item-genre">
  <li><%= link_to "全てのアイテム", items_path %></li>
  <% @genres.each do |genre|%>
    <%= link_to genre_path(genre.id) do %>
    <li><%= genre.name %></li>
    <% end %>
  <% end %>
</ul>

<div class="row">
  <div class="col-12">
    <h1>全てのアイテム　<small>〜全 <%= @item_count.count %> 件〜</small></h1>
  </div>
</div>

<%# 販売ステータスが「販売中」の場合、商品画像大きめ、価格の表示あり %>
<div class="row">
  <% @active_items.each do |item|%>
    <div class="col-3">
      <div id="like-buttons-<%=item.id%>">
        <%= render partial: 'likes/like', locals: { item: item } %>
      </div>
      <%= link_to item_path(item) do%>
        <%= attachment_image_tag item, :image, width:"100%", format: "jpeg", alt: "アイテム画像" %>
        <p>◆<%= item.name %>
        <br><%= converting_to_jpy(item.price) %></p>
      <% end%>
    </div>
  <% end%>
</div>

<div class="row">
  <p><%= paginate @active_items %></p>
</div>

<%# 販売ステータスが「販売停止中」の場合、商品画像小さめ、販売停止中と表示 %>
<div class="row">
  <% @items.each do |item|%>
    <div class="col-2">
      <div id="like-buttons-<%=item.id%>">
        <%= render partial: 'likes/like', locals: { item: item } %>
      </div>
      <%= link_to item_path(item) do%>
        <%= attachment_image_tag item, :image, width:"100%", format: "jpeg", alt: "アイテム画像" %>
        <p class="small">◆<%= item.name %>
        <br>※<%= item.status %></p>
      <% end %>
    </div>
  <% end %>
</div>

<div class="row">
  <p><%= paginate @items %></p>
</div>

app/views/items/show.html.erb
<div class="row">
  <div class="col-5 offset-1">
    <div class="field">
      <%= attachment_image_tag @item, :image, width: "100%", format: "jpeg", class: "mt-5", alt: "アイテム画像" %>
    </div>
  </div>
  <div class="col-5">
      <h1><%= @item.name %></h1>
      <h2><strong><%= simple_format(@item.caption) %></h2>
      <label>◆販売価格</label>
      <h2>　<strong><%= converting_to_jpy(@item.price) %></strong></h2>
      <h2>登録ジャンル：<strong><%= @item.genre.name %></strong></h2>
      <h2>受注状況：<strong><%= @item.status %></strong></h2>
  </div>
</div>

<%# アイテムステータスが「販売中」の場合、カートに追加可能 %>
<% if @item.status == "販売中" %>
  <%= form_for @cart_item do |f| %>
    <div class="row">
      <div class="col-5 offset-6">
        <label>◆サイズを選択</label>
        <h2><%= f.select :size,  [["SS"], ["S"], ["M"], ["L"], ["LL"],["DM"]] %>　<%= link_to "　サイズ選びにつきまして",  homes_size_path, class:"small" %></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-2 offset-1 text-right">
        <label>生地一覧</label>
      </div>
      <div class="col-3 design-select">
        <div style="width:250px; height:200px; overflow:scroll;">
          <% @active_materials.each do |material|%>
            <%= attachment_image_tag material, :image, :fill, 150, 120, format: "jpeg", alt: "生地画像" %>
            <p class="small"><%= material.name %></p>
          <% end %>
        </div>
      </div>
      <div class="col-5">
        <label>◆生地を選択</label>
        <h2><strong><%= f.collection_select :material_id, Material.where(status: 1), :id, :name %></strong></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-2 offset-1 text-right">
        <label>リボン一覧</label>
      </div>
      <div class="col-3 design-select">
        <div style="width:250px; height:200px; overflow:scroll;">
          <% @active_ribbons.each do |ribbon|%>
            <%= attachment_image_tag ribbon, :image, :fill, 150, 120, format: "jpeg", alt: "リボン画像" %>
            <p class="small"><%= ribbon.color %></p>
          <% end %>
        </div>
      </div>
      <div class="col-5">
        <label>◆リボンを選択</label>
        <h2><strong><%= f.collection_select :ribbon_id, Ribbon.where(status: 1), :id, :color %></strong></h2>
      </div>
    </div>

    <div class="row">
      <div class="col-10 offset-1 text-center">
        <%= f.hidden_field :item_id, :value => @item.id %>
        <p><%= f.submit "カートに入れる", class:"btn btn-lg btn-primary" %></p>
        <p><%= link_to "戻る", :back %></p>
      </div>
    </div>
  <% end %>

<%# アイテムステータスが「販売停止中」の場合、戻るボタンを表示 %>
<% else @item.status == "販売停止中" %>
  <p><div class="row">
    <div class="col-10 offset-1 text-center">
      <%= link_to "アイテム一覧へ戻る", items_path, class: "btn btn-primary" %>
    </div>
  </div></p>
<% end %>