config/routes.rb
Rails.application.routes.draw do

  #admin_users devise & end_users devise
  devise_for :admin_users, controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  # top page
  root 'homes#top'
  get 'homes/about'
  get 'homes/size'
  get 'homes/ship_pay'

  # ec page
  resources :items, only: [:index, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :genres, only: [:show]
  delete 'cart_item/destroy_all', to: 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :create, :update, :destroy]
  get 'orders/input_address', to: 'orders#input_address'
  post 'orders/create_address', to: 'orders#create_address'
  post 'orders/create_session', to: 'orders#create_session'
  get 'orders/display', to: 'orders#display'
  get 'orders/thanks', to: 'orders#thanks'
  resources :orders, only: [:index, :show, :create]
  
  # end_user mypage
  resources :end_users, only: [:show, :edit, :update, :destroy] do
    resources :likes, only: [:index]
    collection do
      get :confirm
    end
  end
  
  # admin page
  namespace :admin do
    resources :items, only: [:index, :show, :new, :edit, :create, :update]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :materials, only: [:index, :edit, :update, :create]
    resources :ribbons, only: [:index, :edit, :update, :create]
    patch 'orders/:id/production', to: 'orders#production_update', as: 'order_production'
    resources :orders, only: [:index, :show, :update]
    resources :end_users, only: [:index]
  end
  
  # shipping address
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  acts_as_paranoid
  
  validates :last_name, :first_name, presence: true
  validates :last_name_kana, :first_name_kana, format: { with: /\A[ｧ-ﾝﾞﾟ]+\z/, message: 'は半角ｶﾅで入力してください' } #半角ｶﾀｶﾅ
  validates :zipcode, format: { with: /\A\d{7}\z/, message: 'は7桁で入力してください'}  #半角英数字７桁
  validates :address, presence: true
  validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'は10桁か11桁で入力してください' } #半角英数字10桁か11桁
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin_user!

  def index
    @end_users = EndUser.with_deleted
  end
end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :zipcode, :address, :phone_number, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  before_action :ensure_end_user, { only: [:show, :edit] }

  def show
    @end_user = EndUser.find(params[:id])
  end

  def confirm
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
  if @end_user.update(end_user_params)
    redirect_to end_user_path(@end_user), info: "【登録情報を編集しました】"
  else
    render :edit
  end
end

def destroy
  end_user = EndUser.find(params[:id])
  end_user.destroy
  redirect_to root_path, danger: "【退会しました】"
end

private
  def end_user_params
    params.require(:end_user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :zipcode, :address, :phone_number, :email)
  end

  def ensure_end_user
    @end_user = EndUser.find(params[:id])
    if current_end_user.id != @end_user.id
      redirect_to root_path, danger: "【ユーザーログインしてください】"
    end
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/end_users/confirm.html.erb
<div class="row">
  <div class="col-6 offset-3">
    <h1><strong>本当に退会しますか？</strong></h1>
    <br>
    <h4 class="text-center">
    退会すると、登録したユーザー情報や
    <br>
    これまでの購入履歴が閲覧できなくなります。
    <br>
    <br>
    それでもよろしければ、
    <br>
    「退会する」をクリックしてください。
    </h4>
    <br>
    <p class="text-center">
      <%= link_to '退会しない', root_path, class:"btn btn-primary" %>
      <%= link_to "退会する",end_user_path(current_end_user), class: "btn btn-warning", method: :delete, "data-confirm" => "退会してもよろしいですか？" %>
    </p>
  </div>
</div>

app/views/end_users/edit.html.erb
<div class="row">
  <div class="col-8 offset-2">
    <h1>登録情報編集</h1>
    <%= link_to '退会する', confirm_end_users_path, class:"btn-sm btn-primary" %>
  </div>
</div>

<%= form_for(@end_user) do |f| %>
  <div class="row">
    <div class="col-8 offset-2">
    <%= render 'layouts/error_messages', model: f.object %>
      <table class="table table-bordered">
        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name %><%= f.text_field :first_name %></td>
        </tr>
        <tr>
          <td>ﾌﾘｶﾞﾅ</td>
          <td><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :zipcode, placeholder:"半角英数字 ハイフン不要" %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= f.text_field :address, size: 40 %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= f.text_field :phone_number, placeholder:"半角英数字 ハイフン不要" %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email, size: 40 %></td>
        </tr>
      </table>
      
      <p><%= f.submit '編集内容を保存する', class: "btn btn-primary mx-auto d-block " %></p>
    </div>
  </div>
<% end %>

<p class="text-center"><%= link_to "戻る", end_user_path(current_end_user) %></p>

app/views/end_users/show.html.erb
<div class="row">
  <div class="col-10 offset-1">
    <h1>マイページ</h1>
  </div>
</div>

<div class="row">
  <div class="col-5 offset-1">
    <h4><strong>登録情報</strong>
      <%= link_to '編集する', edit_end_user_path(current_end_user.id), class:"btn btn-primary" %>
      <%= link_to 'パスワードを変更する', edit_end_user_registration_path, class:"btn btn-primary" %>
    </h4>
    <table class="table table-bordered ">
      <tr>
        <td width="150">氏名</td>
        <td><%= @end_user.last_name %> <%= @end_user.first_name %></td>
      </tr>
      <tr>
        <td>ﾌﾘｶﾞﾅ</td>
        <td><%= @end_user.last_name_kana %> <%= @end_user.first_name_kana %>
        </td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td>〒<%= @end_user.zipcode.insert(3, "-") %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @end_user.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @end_user.phone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @end_user.email %></td>
      </tr>
    </table>
  </div>
  <div class="col-4 offset-1">
    <h4><strong>配送先　　　</strong><%= link_to '一覧を見る', addresses_path, class:"btn btn-primary" %> </h4>
    <h4><strong>注文履歴　　</strong><%= link_to '一覧を見る', orders_path, class:"btn btn-primary" %> </h4>
    <h4><strong>お気に入り　</strong><%= link_to '一覧を見る', end_user_likes_path(current_end_user), class:"btn btn-primary" %> </h4>
  </div>
</div>